---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: <YOR_PATH_TO_SSH_KEY>
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  children:
    proxy:
      hosts:
        vm-proxy:
          ansible_host: <YOUR_NAT_IP>

    web:
      hosts:
        vm-web-1:
          ansible_host: <YOUR_NAT_IP>
        vm-web-2:
          ansible_host: <YOUR_NAT_IP>
